# Generated by Django 5.2.8 on 2025-11-11 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='Level number', unique=True)),
                ('exp_required', models.IntegerField(help_text='Total EXP required to reach this level')),
                ('bonus_description', models.TextField(blank=True, help_text='Description of bonus or reward for reaching this level', null=True)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='ExpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('quest', 'Quest'), ('assignment', 'Assignment'), ('participation', 'Participation'), ('bonus', 'Bonus'), ('admin', 'Admin Grant'), ('other', 'Other')], default='other', max_length=20)),
                ('exp_earned', models.IntegerField(help_text='Amount of EXP earned')),
                ('description', models.TextField(help_text='Description of the activity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EXP Log',
                'verbose_name_plural': 'EXP Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_explog_user_id_264385_idx'), models.Index(fields=['activity_type'], name='core_explog_activit_df1b00_idx')],
            },
        ),
    ]
