# Generated by Django 5.2.8 on 2025-11-11 03:09

from django.db import migrations


def create_initial_levels(apps, schema_editor):
    """
    Membuat data initial untuk level curve
    EXP required: 0, 100, 250, 450, 700, 1000, 1350, 1750, 2200, 2700, 3250, 3850, 4500, 5200, 6000
    """
    Level = apps.get_model('core', 'Level')
    
    level_data = [
        (1, 0, "Starting level. Welcome to ClassCraft!"),
        (2, 100, "Level 2 reached! Keep up the good work!"),
        (3, 250, "Level 3 achieved! You're making progress!"),
        (4, 450, "Level 4 unlocked! Great job!"),
        (5, 700, "Level 5 reached! Halfway to level 10!"),
        (6, 1000, "Level 6 achieved! You're getting stronger!"),
        (7, 1350, "Level 7 unlocked! Excellent progress!"),
        (8, 1750, "Level 8 reached! Keep pushing forward!"),
        (9, 2200, "Level 9 achieved! Almost at level 10!"),
        (10, 2700, "Level 10 reached! Double digits milestone!"),
        (11, 3250, "Level 11 achieved! You're a veteran now!"),
        (12, 3850, "Level 12 unlocked! Impressive dedication!"),
        (13, 4500, "Level 13 reached! You're unstoppable!"),
        (14, 5200, "Level 14 achieved! Master level approaching!"),
        (15, 6000, "Level 15 reached! You are a true master!"),
    ]
    
    for level_num, exp_required, bonus_desc in level_data:
        Level.objects.get_or_create(
            level=level_num,
            defaults={
                'exp_required': exp_required,
                'bonus_description': bonus_desc
            }
        )


def reverse_create_initial_levels(apps, schema_editor):
    """Reverse migration - hapus semua level"""
    Level = apps.get_model('core', 'Level')
    Level.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_levels, reverse_create_initial_levels),
    ]
