# Generated by Django 5.2.8 on 2025-11-11 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dungeon_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sidequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Judul tugas', max_length=200)),
                ('description', models.TextField(help_text='Deskripsi tugas')),
                ('instructions', models.TextField(help_text='Instruksi pengerjaan tugas')),
                ('due_date', models.DateTimeField(help_text='Batas waktu pengumpulan')),
                ('exp_reward', models.IntegerField(default=200, help_text='EXP yang diberikan untuk submission tepat waktu')),
                ('late_exp_reward', models.IntegerField(default=100, help_text='EXP yang diberikan untuk submission terlambat')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sidequest',
                'verbose_name_plural': 'Sidequests',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='SidequestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_file', models.FileField(help_text='File yang dikumpulkan', upload_to='submissions/%Y/%m/%d/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.IntegerField(blank=True, help_text='Nilai yang diberikan (0-100)', null=True)),
                ('exp_earned', models.IntegerField(default=0, help_text='EXP yang diperoleh dari submission')),
                ('feedback', models.TextField(blank=True, help_text='Feedback dari admin', null=True)),
                ('sidequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.sidequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sidequest_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sidequest Submission',
                'verbose_name_plural': 'Sidequest Submissions',
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'sidequest')},
            },
        ),
    ]
