# Generated by Django 5.2.8 on 2025-11-11 03:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sidequest_sidequestsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mini_boss', 'Mini Boss'), ('mid_boss', 'Mid Boss'), ('last_boss', 'Last Boss')], help_text='Tipe boss battle', max_length=20)),
                ('name', models.CharField(help_text='Nama boss/ujian', max_length=200)),
                ('description', models.TextField(help_text='Deskripsi boss battle')),
                ('base_score', models.IntegerField(help_text='Nilai asli (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_score', models.IntegerField(blank=True, help_text='Nilai akhir setelah bonus (auto-calculated)', null=True)),
                ('battle_date', models.DateField(help_text='Tanggal battle/ujian')),
                ('bonus_applied', models.IntegerField(default=0, help_text='Bonus yang diterapkan berdasarkan level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Player yang melakukan battle', on_delete=django.db.models.deletion.CASCADE, related_name='boss_battles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boss',
                'verbose_name_plural': 'Bosses',
                'ordering': ['-battle_date'],
            },
        ),
    ]
