# Generated by Django 5.2.8 on 2025-11-11 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_boss'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Punishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('plagiarism', 'Plagiarism'), ('cheating', 'Cheating'), ('late_submission', 'Late Submission'), ('absence', 'Absence')], help_text='Tipe punishment', max_length=20)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], help_text='Tingkat keparahan', max_length=20)),
                ('description', models.TextField(help_text='Deskripsi punishment')),
                ('exp_penalty', models.IntegerField(default=0, help_text='EXP yang dikurangi (penalty)')),
                ('status_effect', models.CharField(blank=True, choices=[('curse', 'Curse'), ('weakness', 'Weakness'), ('silence', 'Silence'), ('fatigue', 'Fatigue')], help_text='Status effect yang diterapkan (optional)', max_length=20, null=True)),
                ('duration_days', models.IntegerField(default=0, help_text='Durasi punishment dalam hari')),
                ('resolved', models.BooleanField(default=False, help_text='Apakah punishment sudah diselesaikan')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Bukti atau data tambahan (JSON)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='Admin yang membuat punishment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punishments_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Player yang dihukum', on_delete=django.db.models.deletion.CASCADE, related_name='punishments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punishment',
                'verbose_name_plural': 'Punishments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(choices=[('curse', 'Curse'), ('weakness', 'Weakness'), ('silence', 'Silence'), ('fatigue', 'Fatigue')], help_text='Tipe status effect', max_length=20)),
                ('description', models.TextField(help_text='Deskripsi effect')),
                ('exp_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplier untuk EXP (1.0 = normal, <1.0 = reduced, >1.0 = bonus)', max_digits=3)),
                ('blocks_activities', models.JSONField(blank=True, default=list, help_text='Aktivitas yang diblokir (list of activity types)')),
                ('start_date', models.DateTimeField(help_text='Tanggal mulai effect')),
                ('end_date', models.DateTimeField(blank=True, help_text='Tanggal berakhir effect (null = permanent until resolved)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Apakah effect masih aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Player yang terkena effect', on_delete=django.db.models.deletion.CASCADE, related_name='status_effects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status Effect',
                'verbose_name_plural': 'Status Effects',
                'ordering': ['-start_date'],
            },
        ),
    ]
