# Generated by Django 5.2.8 on 2025-11-11 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_punishment_statuseffect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['user', '-created_at'], name='core_attend_user_id_7832d4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['dungeon', 'attended'], name='core_attend_dungeon_0ccc39_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attended', '-created_at'], name='core_attend_attende_44e739_idx'),
        ),
        migrations.AddIndex(
            model_name='boss',
            index=models.Index(fields=['user', '-battle_date'], name='core_boss_user_id_c88988_idx'),
        ),
        migrations.AddIndex(
            model_name='boss',
            index=models.Index(fields=['type', '-battle_date'], name='core_boss_type_6baddc_idx'),
        ),
        migrations.AddIndex(
            model_name='boss',
            index=models.Index(fields=['battle_date'], name='core_boss_battle__a1b648_idx'),
        ),
        migrations.AddIndex(
            model_name='dungeon',
            index=models.Index(fields=['status', '-scheduled_date'], name='core_dungeo_status_d525d6_idx'),
        ),
        migrations.AddIndex(
            model_name='dungeon',
            index=models.Index(fields=['scheduled_date'], name='core_dungeo_schedul_c9c8fa_idx'),
        ),
        migrations.AddIndex(
            model_name='punishment',
            index=models.Index(fields=['user', '-created_at'], name='core_punish_user_id_03bca2_idx'),
        ),
        migrations.AddIndex(
            model_name='punishment',
            index=models.Index(fields=['type', 'resolved'], name='core_punish_type_f676e7_idx'),
        ),
        migrations.AddIndex(
            model_name='punishment',
            index=models.Index(fields=['resolved', '-created_at'], name='core_punish_resolve_64cfab_idx'),
        ),
        migrations.AddIndex(
            model_name='punishment',
            index=models.Index(fields=['severity'], name='core_punish_severit_caafba_idx'),
        ),
        migrations.AddIndex(
            model_name='sidequestsubmission',
            index=models.Index(fields=['user', '-submitted_at'], name='core_sidequ_user_id_4a33a8_idx'),
        ),
        migrations.AddIndex(
            model_name='sidequestsubmission',
            index=models.Index(fields=['sidequest', '-submitted_at'], name='core_sidequ_sideque_453c34_idx'),
        ),
        migrations.AddIndex(
            model_name='sidequestsubmission',
            index=models.Index(fields=['grade', '-submitted_at'], name='core_sidequ_grade_5083ef_idx'),
        ),
        migrations.AddIndex(
            model_name='statuseffect',
            index=models.Index(fields=['user', 'is_active'], name='core_status_user_id_f4c1cd_idx'),
        ),
        migrations.AddIndex(
            model_name='statuseffect',
            index=models.Index(fields=['is_active', '-start_date'], name='core_status_is_acti_c388c2_idx'),
        ),
        migrations.AddIndex(
            model_name='statuseffect',
            index=models.Index(fields=['effect_type', 'is_active'], name='core_status_effect__f87ced_idx'),
        ),
    ]
